import { TravelData } from '@/types/travel';
import { LOCATIONS } from './locations';

export const travelData: TravelData = {
  title: '다낭 여행',
  startDate: '2026-01-15T10:00:00+09:00', // 한국 시간
  endDate: '2026-01-19T08:00:00+09:00',
  days: [
    {
      day: 1,
      date: '2026-01-15',
      dayOfWeek: '목',
      activities: [
        {
          id: '1-1',
          time: '10:00',
          title: '집에서 출발',
        },
        {
          id: '1-2',
          time: '15:00',
          title: '공항 미팅 (노랑풍선)',
          description: '인천 국제공항 제2터미널 3층 A카운터 1번 출입문앞 노랑풍선테이블 3번,4번',
          imageUrl: '/images/image.png',
          location: LOCATIONS.INCHEON_AIRPORT,
        },
        {
          id: '1-3',
          time: '18:30',
          title: '인천 출발',
          location: LOCATIONS.INCHEON_AIRPORT,
        },
        {
          id: '1-4',
          time: '21:30',
          title: '다낭 도착',
          location: LOCATIONS.DANANG_AIRPORT,
        },
        {
          id: '1-5',
          time: '22:00',
          title: '호텔 도착',
          description: '다낭 윈덤솔레일',
          location: LOCATIONS.DANANG_HOTEL,
        },
        {
          id: '1-6',
          time: '23:00',
          title: '야식/휴식',
          location: LOCATIONS.DANANG_HOTEL,
        },
      ],
      meals: [],
    },
    {
      day: 2,
      date: '2026-01-16',
      dayOfWeek: '금',
      activities: [
        {
          id: '2-1',
          time: '09:00',
          title: '호텔 조식',
          location: LOCATIONS.DANANG_HOTEL,
        },
        {
          id: '2-2',
          time: '10:00',
          title: '가이드 미팅',
          location: LOCATIONS.DANANG_HOTEL,
        },
        {
          id: '2-3',
          time: '10:30',
          title: '베트남 전통 마사지',
          description: '120분',
          tip: '팁 4$',
          imageUrl: '/images/image-massage.png',
          location: LOCATIONS.DANANG_HOTEL,
        },
        {
          id: '2-4',
          time: '13:30',
          title: '마블마운틴(오행산) 관광',
          imageUrl: '/images/image-1.png',
          location: LOCATIONS.MARBLE_MOUNTAINS,
        },
        {
          id: '2-5',
          time: '15:30',
          title: '베트남 전통 바구니배',
          description: '매너팁 별도',
          imageUrl: '/images/image-2.png',
          location: LOCATIONS.HOI_AN_ANCIENT_TOWN,
        },
        {
          id: '2-6',
          time: '17:00',
          title: '호이안 투본강 투어',
          imageUrl: '/images/image-3.png',
          location: LOCATIONS.HOI_AN_ANCIENT_TOWN,
        },
        {
          id: '2-7',
          time: '18:00',
          title: '호이안 구시가지',
          imageUrl: '/images/image-4.png',
          location: LOCATIONS.HOI_AN_ANCIENT_TOWN,
        },
        {
          id: '2-8',
          time: '18:30',
          title: '풍흥의 집',
          imageUrl: '/images/image-5.png',
          location: LOCATIONS.PHUN_HUNG_HOUSE,
        },
        {
          id: '2-9',
          time: '19:00',
          title: '일본 내원교',
          imageUrl: '/images/image-6.png',
          location: LOCATIONS.JAPANESE_BRIDGE,
        },
        {
          id: '2-10',
          time: '19:30',
          title: '광조 회관',
          imageUrl: '/images/image-7.png',
          location: LOCATIONS.CANTONESE_HALL,
        },
        {
          id: '2-11',
          time: '20:00',
          title: '호이안 야경',
          imageUrl: '/images/image-8.png',
          location: LOCATIONS.HOI_AN_ANCIENT_TOWN,
        },
        {
          id: '2-12',
          time: '20:30',
          title: '씨클로',
          imageUrl: '/images/image-9.png',
          location: LOCATIONS.HOI_AN_ANCIENT_TOWN,
        },
        {
          id: '2-13',
          time: '22:00',
          title: '다낭으로 이동',
          location: LOCATIONS.DANANG_HOTEL,
        },
        {
          id: '2-14',
          time: '23:30',
          title: '야식/휴식',
          location: LOCATIONS.DANANG_HOTEL,
        },
      ],
      meals: [
        { type: '중식', menu: '장어정식' },
        { type: '석식', menu: '호이안전통식' },
      ],
    },
    {
      day: 3,
      date: '2026-01-17',
      dayOfWeek: '토',
      activities: [
        {
          id: '3-1',
          time: '09:00',
          title: '호텔 조식',
          location: LOCATIONS.DANANG_HOTEL,
        },
        {
          id: '3-2',
          time: '10:00',
          title: '베트남 최대 테마파크 바나힐스 관광',
          imageUrl: '/images/image-10.png',
          location: LOCATIONS.BA_NA_HILLS,
        },
        {
          id: '3-3',
          time: '15:00',
          title: '베트남 전통 위즐커피',
          description: '1인 1잔',
          location: LOCATIONS.DANANG_HOTEL,
        },
        {
          id: '3-4',
          time: '16:00',
          title: '미케비치 자유시간',
          description: '세계에서 가장 매력적인 해변',
          imageUrl: '/images/image-11.png',
          location: LOCATIONS.MY_KHE_BEACH,
        },
        {
          id: '3-5',
          time: '19:00',
          title: '한강유람선',
          location: LOCATIONS.LOVE_BRIDGE,
        },
        {
          id: '3-6',
          time: '21:00',
          title: '야식/휴식',
          location: LOCATIONS.DANANG_HOTEL,
        },
      ],
      meals: [
        { type: '중식', menu: '퓨전한식뷔페' },
        { type: '석식', menu: '무제한삼겹살' },
      ],
    },
    {
      day: 4,
      date: '2026-01-18',
      dayOfWeek: '일',
      activities: [
        {
          id: '4-1',
          time: '09:00',
          title: '호텔 조식 및 체크아웃',
          location: LOCATIONS.DANANG_HOTEL,
        },
        {
          id: '4-2',
          time: '10:00',
          title: '쇼핑센터 방문',
          location: LOCATIONS.HAN_MARKET,
        },
        {
          id: '4-3',
          time: '13:00',
          title: '다낭 대성당',
          location: LOCATIONS.DANANG_CATHEDRAL,
        },
        {
          id: '4-4',
          time: '14:00',
          title: '선짜 마리나 카페',
          description: '다낭의 산토리니 감성 포토존! 1인 1잔',
          imageUrl: '/images/image-12.png',
          location: LOCATIONS.SUNTRA_MARINA,
        },
        {
          id: '4-5',
          time: '15:30',
          title: '영흥사 (린엄사)',
          imageUrl: '/images/image-13.png',
          location: LOCATIONS.LINH_UNG_PAGODA,
        },
        {
          id: '4-6',
          time: '17:00',
          title: '사랑의 부두',
          imageUrl: '/images/image-14.png',
          location: LOCATIONS.LOVE_BRIDGE,
        },
        {
          id: '4-7',
          time: '19:00',
          title: '다낭 야시장',
          imageUrl: '/images/image-15.png',
          location: LOCATIONS.HAN_MARKET,
        },
        {
          id: '4-8',
          time: '23:20',
          title: '다낭 출발',
          location: LOCATIONS.DANANG_AIRPORT,
        },
      ],
      meals: [
        { type: '중식', menu: '마담란(현지식)' },
        { type: '석식', menu: '노니보쌈&쭈꾸미볶음' },
      ],
    },
    {
      day: 5,
      date: '2026-01-19',
      dayOfWeek: '월',
      activities: [
        {
          id: '5-1',
          time: '05:35',
          title: '인천 도착',
          location: LOCATIONS.INCHEON_AIRPORT,
        },
        {
          id: '5-2',
          time: '08:00',
          title: '집으로 복귀',
          location: LOCATIONS.INCHEON_AIRPORT,
        },
      ],
      meals: [],
    },
  ],
};
